version: '3.8'

services:
  flask_app1:
    build: .
    environment:
      - DB_HOST=db_master
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=testdb
    depends_on:
      - db_master
    networks:
      - app_network
    restart: always

  flask_app2:
    build: .
    environment:
      - DB_HOST=db_master
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=testdb
    depends_on:
      - db_master
    networks:
      - app_network
    restart: always

  db_master:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testdb
    volumes:
      - ./mysql/master/my.cnf:/etc/mysql/my.cnf
      - db_master_data:/var/lib/mysql
    networks:
      - app_network
    restart: always

  db_slave:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testdb
    volumes:
      - ./mysql/slave/my.cnf:/etc/mysql/my.cnf
      - db_slave_data:/var/lib/mysql
    depends_on:
      - db_master
    networks:
      - app_network
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask_app1
      - flask_app2
    networks:
      - app_network
    restart: always

volumes:
  db_master_data:
  db_slave_data:

networks:
  app_network:
    driver: bridge